name = "ariady-putra-emurgo/aiken_primitive_exercise"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ariady-putra-emurgo/aiken_primitive_exercise'"

[repository]
user = "ariady-putra-emurgo"
project = "aiken_primitive_exercise"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
